name: .NET

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore smsmanager/smsmanager.csproj
    - name: Build
      run: dotnet publish smsmanager/smsmanager.csproj -c Release -r linux-arm64 --self-contained /p:PublishSingleFile=true
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
          name: WiFismsmanager
          path: smsmanager/bin/Release/net6.0/linux-arm64/publish/
