name: .NET

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install .NET 8.0
      run: |
        curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh --channel 8.0
        echo "$HOME/.dotnet" >> $GITHUB_PATH
    - name: Restore dependencies
      run: dotnet restore smsmanager/smsmanager.csproj
    - name: Build
      run: dotnet publish smsmanager/smsmanager.csproj -c Release -r linux-arm64 --self-contained /p:PublishSingleFile=true
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
          name: WiFismsmanager
          path: smsmanager/bin/Release/net8.0/linux-arm64/publish/
